Update 4-reload_gunicorn_no_downtime

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -1,3 +1,8 @@
 #!/usr/bin/env bash
-# Script to reload Gunicorn in a graceful way
-kill -HUP
+# Gracefully restart & update gunicorn workers
+if pkill -HUP gunicorn; then
+        echo "Gunicorn workers were gracefully reloaded."
+else
+        echo "Error: Unable to reload Gunicorn workers." >&2
+        exit 1
+fi
